<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Mimo</Company>
    <PackageId>Mimo.AppStoreServerLibrary</PackageId>
    <Version>0.1.1</Version>
    <Authors>Mimo</Authors>
    <Title>Mimo.AppStoreServerLibrary</Title>
    <Description>An unofficial .NET SDK for App Store Server Notifications and API</Description>
    <Copyright>Copyright © Mimo GmbH 2024</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/getmimo/app-store-server-library-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/getmimo/app-store-server-library-dotnet</RepositoryUrl>
    <PackageTags>Apple, StoreKit 2, App Store Server Notifications, App Store Server API, App Store Server Library, AppStore</PackageTags>
    <IsPackable>true</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyName>Mimo.AppStoreServerLibrary</AssemblyName>
    <RootNamespace>Mimo.AppStoreServerLibrary</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <Target Name="Husky" BeforeTargets="Restore;CollectPackageReferences" Condition="'$(HUSKY)' != 0">
    <Exec Command="dotnet tool restore" StandardOutputImportance="Low" StandardErrorImportance="High" />
    <Exec Command="dotnet husky install" StandardOutputImportance="Low" StandardErrorImportance="High" WorkingDirectory=".." />
  </Target>
</Project>
